-- a
SELECT COUNTRY_NAME FROM COUNTRIES;

-- b
SELECT JOB_TITLE
FROM JOBS;

-- c
SELECT MANAGER_ID
FROM EMPLOYEES;

-- d
SELECT DISTINCT CITY
FROM LOCATIONS;

-- e
SELECT LOCATION_ID, (STREET_ADDRESS||' | '||CITY||' | '||STATE_PROVINCE||' | '||POSTAL_CODE) ADDRESS 
FROM LOCATIONS;