-- a
SELECT *
FROM EMPLOYEES
WHERE HIRE_DATE < '01-JAN-2004';

-- b
SELECT *
FROM LOCATIONS
WHERE COUNTRY_ID IN ('CA', 'DE', 'UK');

-- c
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NULL;

-- d
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE LAST_NAME LIKE 'a%';

-- e
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE LAST_NAME LIKE 's%n';

-- f
SELECT DEPARTMENT_NAME
FROM DEPARTMENTS
WHERE MANAGER_ID = 100;

-- g
SELECT (FIRST_NAME||' '||LAST_NAME) FULL_NAME
FROM EMPLOYEES
WHERE JOB_ID='AD_PRES' AND SALARY >= 23000;

-- h
SELECT (FIRST_NAME||' '||LAST_NAME) FULL_NAME
FROM EMPLOYEES
WHERE LAST_NAME NOT LIKE '%s%';

-- i
SELECT (FIRST_NAME||' '||LAST_NAME) FULL_NAME, COMMISSION_PCT
FROM EMPLOYEES
WHERE COMMISSION_PCT <= .30;

-- j
SELECT (FIRST_NAME||' '||LAST_NAME) FULL_NAME
FROM EMPLOYEES
WHERE HIRE_DATE > '01-JAN-1998';

-- k
SELECT (FIRST_NAME||' '||LAST_NAME) FULL_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN '01-JAN-2004' AND '31-DEC-2004';



