-- a
SELECT (FIRST_NAME||' '||LAST_NAME) FULL_NAME, SALARY, COMMISSION_PCT
FROM EMPLOYEES
WHERE JOB_ID='AD_PRES'
ORDER BY SALARY DESC;

-- b
SELECT COUNTRY_NAME
FROM COUNTRIES
ORDER BY COUNTRY_NAME ASC;

-- extra practise
-- ea
SELECT LAST_NAME, SALARY
FROM EMPLOYEES
ORDER BY SALARY DESC, LAST_NAME ASC;

-- eb
SELECT JOB_TITLE, (MAX_SALARY - MIN_SALARY) DIFF_SALARY
FROM JOBS
ORDER BY DIFF_SALARY DESC;