-- a
SELECT 
UPPER(SUBSTR(COUNTRY_NAME, 1, 3)) FIRST_THREE,
UPPER(SUBSTR(COUNTRY_NAME, LENGTH(COUNTRY_NAME)-3+1, 3)) LAST_THREE
FROM COUNTRIES;

-- b
SELECT LPAD((FIRST_NAME||' '||LAST_NAME), 60, '*') STAR_PADDED_NAME
FROM EMPLOYEES;

-- c
SELECT JOB_TITLE
FROM JOBS 
WHERE INSTR(LOWER(JOB_TITLE), 'manager') > 0;

-- extra practise queries
-- ea
SELECT CONCAT(CONCAT(TRIM(FIRST_NAME), ' '),LAST_NAME) FULL_NAME
FROM EMPLOYEES;

-- eb
SELECT CONCAT(CONCAT(TRIM(REPLACE(FIRST_NAME, FIRST_NAME, 'Jamie')), ' '),LAST_NAME) FULL_NAME
FROM EMPLOYEES
WHERE UPPER(LAST_NAME) LIKE 'SULLIVAN';