-- a
SELECT 
FIRST_NAME,
ROUND(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)/12, 2) "YEARS EMPLOYED"
FROM EMPLOYEES;

-- b
SELECT 
(FIRST_NAME||' '||LAST_NAME) "FULL NAME",
HIRE_DATE,
(TRUNC(ADD_MONTHS(HIRE_DATE, 1), 'MONTH') - HIRE_DATE) "1ST MONTH WORKING DAYS"
FROM EMPLOYEES;

-- extra practise 
-- ea
SELECT
HIRE_DATE,
ROUND(HIRE_DATE, 'MONTH') RM,
TRUNC(HIRE_DATE, 'MONTH') TM,
FROM EMPLOYEES
WHERE ROUND(HIRE_DATE, 'MONTH') <> TRUNC(HIRE_DATE, 'MONTH');

-- eb
SELECT
HIRE_DATE,
ROUND(HIRE_DATE, 'YEAR') RY,
TRUNC(HIRE_DATE, 'YEAR') TY
FROM EMPLOYEES
WHERE ROUND(HIRE_DATE, 'YEAR') <> TRUNC(HIRE_DATE, 'YEAR');

-- ec
SELECT
HIRE_DATE,
HIRE_DATE-1 "PREVIOUS DAY",
HIRE_DATE+1 "NEXT DAY"
FROM EMPLOYEES;